### ISSUE TITLE
eat your own dogfood

### ISSUE THREAD

**Issue by teepark** [duplys/git-issues#3]
github issues on a ticket tracker? really?

**Comment by jwiegley** [comment]
Very useful.

**Comment by teepark** [comment]
I think you're missing the point. The first project to use the git-issues ticket tracker should be git-issues. I'm not going to use any ticket tracker for which the author opts instead to use github issues, nor, I think, will most developers.

http://en.wikipedia.org/wiki/Eating_one's_own_dog_food

**Comment by jwiegley** [comment]
However, you are making assumptions.  I never "turned on" the issue tracker here at GitHub, it was just on because I use it for some of my other projects.  Also, sometimes it's easier for other people to submit issues via this interface than to require that they pull down git-issues and submit their issue as a patch.

**Comment by jean** [comment]
What I would love is for the github issue tracker to be able to use git-issues as a backend. 
What would need to happen for that to be possible?

**Comment by jwiegley** [comment]
Do you work for GitHub?  That would make it happen. :)

John (from my iPhone)

**Comment by jean** [comment]
I don't, but mojombo does (rather!): see https://github.com/github/gollum/issues/223
